version: "3.7"

services:
  frontend:
    build: frontend/my-app
    ports:
      - 3000:3000
    networks: 
      - deploy_network
    depends_on:
      - backend

  backend:
    build: backend
    ports:
      - 8000:8000
    networks: 
      - deploy_network
    volumes:
      - ./backend:/app
    

networks:
  deploy_network:
    driver: bridge
